//
// ProjectsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class ProjectsAPI: APIBase {
    /**

     - parameter id: (path)  
     - parameter authorization: (header) Authorization header parameter (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiProjectsByIdDislikePut(id: Int32, authorization: String? = nil, completion: @escaping ((_ error: Error?) -> Void)) {
        apiProjectsByIdDislikePutWithRequestBuilder(id: id, authorization: authorization).execute { (response, error) -> Void in
            completion(error);
        }
    }


    /**
     - PUT /api/projects/{id}/dislike
     
     - parameter id: (path)  
     - parameter authorization: (header) Authorization header parameter (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func apiProjectsByIdDislikePutWithRequestBuilder(id: Int32, authorization: String? = nil) -> RequestBuilder<Void> {
        var path = "/api/projects/{id}/dislike"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter id: (path)  
     - parameter authorization: (header) Authorization header parameter (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiProjectsByIdGet(id: Int32, authorization: String? = nil, completion: @escaping ((_ data: Project?,_ error: Error?) -> Void)) {
        apiProjectsByIdGetWithRequestBuilder(id: id, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /api/projects/{id}
     - examples: [{contentType=application/json, example={
  "goal" : 123,
  "imageId" : 123,
  "mainImageUrlSmall" : "aeiou",
  "isLiked" : true,
  "description" : "aeiou",
  "shortDescription" : "aeiou",
  "creationDate" : "2000-01-23T04:56:07.000+00:00",
  "otherImagesUrl" : [ "aeiou" ],
  "otherImagesUrlSmall" : [ "aeiou" ],
  "donatorsCount" : 123,
  "likesCount" : 123,
  "deleted" : true,
  "reachedDate" : "2000-01-23T04:56:07.000+00:00",
  "reached" : 123,
  "name" : "aeiou",
  "treePrice" : 1.3579000000000001069366817318950779736042022705078125,
  "currency" : "aeiou",
  "id" : 123,
  "tag" : "aeiou",
  "mainImageUrl" : "aeiou",
  "status" : "aeiou",
  "finishedDate" : "2000-01-23T04:56:07.000+00:00"
}}]
     
     - parameter id: (path)  
     - parameter authorization: (header) Authorization header parameter (optional)

     - returns: RequestBuilder<Project> 
     */
    open class func apiProjectsByIdGetWithRequestBuilder(id: Int32, authorization: String? = nil) -> RequestBuilder<Project> {
        var path = "/api/projects/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Project>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter id: (path)  
     - parameter authorization: (header) Authorization header parameter (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiProjectsByIdLikePut(id: Int32, authorization: String? = nil, completion: @escaping ((_ error: Error?) -> Void)) {
        apiProjectsByIdLikePutWithRequestBuilder(id: id, authorization: authorization).execute { (response, error) -> Void in
            completion(error);
        }
    }


    /**
     - PUT /api/projects/{id}/like
     
     - parameter id: (path)  
     - parameter authorization: (header) Authorization header parameter (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func apiProjectsByIdLikePutWithRequestBuilder(id: Int32, authorization: String? = nil) -> RequestBuilder<Void> {
        var path = "/api/projects/{id}/like"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     
     
     - parameter status: (query)  (optional)
     - parameter page: (query)  (optional)
     - parameter pagesize: (query)  (optional)
     - parameter authorization: (header) Authorization header parameter (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiProjectsGet(status: String? = nil, page: Int32? = nil, pagesize: Int32? = nil, authorization: String? = nil, completion: @escaping ((_ data: [Project]?,_ error: Error?) -> Void)) {
        apiProjectsGetWithRequestBuilder(status: status, page: page, pagesize: pagesize, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     
     - GET /api/projects
     - examples: [{contentType=application/json, example=[ {
  "goal" : 123,
  "imageId" : 123,
  "mainImageUrlSmall" : "aeiou",
  "isLiked" : true,
  "description" : "aeiou",
  "shortDescription" : "aeiou",
  "creationDate" : "2000-01-23T04:56:07.000+00:00",
  "otherImagesUrl" : [ "aeiou" ],
  "otherImagesUrlSmall" : [ "aeiou" ],
  "donatorsCount" : 123,
  "likesCount" : 123,
  "deleted" : true,
  "reachedDate" : "2000-01-23T04:56:07.000+00:00",
  "reached" : 123,
  "name" : "aeiou",
  "treePrice" : 1.3579000000000001069366817318950779736042022705078125,
  "currency" : "aeiou",
  "id" : 123,
  "tag" : "aeiou",
  "mainImageUrl" : "aeiou",
  "status" : "aeiou",
  "finishedDate" : "2000-01-23T04:56:07.000+00:00"
} ]}]
     
     - parameter status: (query)  (optional)
     - parameter page: (query)  (optional)
     - parameter pagesize: (query)  (optional)
     - parameter authorization: (header) Authorization header parameter (optional)

     - returns: RequestBuilder<[Project]> 
     */
    open class func apiProjectsGetWithRequestBuilder(status: String? = nil, page: Int32? = nil, pagesize: Int32? = nil, authorization: String? = nil) -> RequestBuilder<[Project]> {
        let path = "/api/projects"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "status": status, 
            "page": page?.encodeToJSON(), 
            "pagesize": pagesize?.encodeToJSON()
        ])
        
        let nillableHeaders: [String: Any?] = [
            "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Project]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter page: (query)  (optional)
     - parameter pagesize: (query)  (optional)
     - parameter authorization: (header) Authorization header parameter (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiProjectsUserGet(page: Int32? = nil, pagesize: Int32? = nil, authorization: String? = nil, completion: @escaping ((_ data: [Project]?,_ error: Error?) -> Void)) {
        apiProjectsUserGetWithRequestBuilder(page: page, pagesize: pagesize, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /api/projects/user
     - examples: [{contentType=application/json, example=[ {
  "goal" : 123,
  "imageId" : 123,
  "mainImageUrlSmall" : "aeiou",
  "isLiked" : true,
  "description" : "aeiou",
  "shortDescription" : "aeiou",
  "creationDate" : "2000-01-23T04:56:07.000+00:00",
  "otherImagesUrl" : [ "aeiou" ],
  "otherImagesUrlSmall" : [ "aeiou" ],
  "donatorsCount" : 123,
  "likesCount" : 123,
  "deleted" : true,
  "reachedDate" : "2000-01-23T04:56:07.000+00:00",
  "reached" : 123,
  "name" : "aeiou",
  "treePrice" : 1.3579000000000001069366817318950779736042022705078125,
  "currency" : "aeiou",
  "id" : 123,
  "tag" : "aeiou",
  "mainImageUrl" : "aeiou",
  "status" : "aeiou",
  "finishedDate" : "2000-01-23T04:56:07.000+00:00"
} ]}]
     
     - parameter page: (query)  (optional)
     - parameter pagesize: (query)  (optional)
     - parameter authorization: (header) Authorization header parameter (optional)

     - returns: RequestBuilder<[Project]> 
     */
    open class func apiProjectsUserGetWithRequestBuilder(page: Int32? = nil, pagesize: Int32? = nil, authorization: String? = nil) -> RequestBuilder<[Project]> {
        let path = "/api/projects/user"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "page": page?.encodeToJSON(), 
            "pagesize": pagesize?.encodeToJSON()
        ])
        
        let nillableHeaders: [String: Any?] = [
            "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Project]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

}
