//
// PaymentsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class PaymentsAPI: APIBase {
    /**

     - parameter projectId: (query)  (optional)
     - parameter amount: (query)  (optional)
     - parameter currency: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiPaymentsWebmoneyPost(projectId: Int32? = nil, amount: Double? = nil, currency: Int32? = nil, completion: @escaping ((_ error: Error?) -> Void)) {
        apiPaymentsWebmoneyPostWithRequestBuilder(projectId: projectId, amount: amount, currency: currency).execute { (response, error) -> Void in
            completion(error);
        }
    }


    /**
     - POST /api/Payments/webmoney
     
     - parameter projectId: (query)  (optional)
     - parameter amount: (query)  (optional)
     - parameter currency: (query)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func apiPaymentsWebmoneyPostWithRequestBuilder(projectId: Int32? = nil, amount: Double? = nil, currency: Int32? = nil) -> RequestBuilder<Void> {
        let path = "/api/Payments/webmoney"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "projectId": projectId?.encodeToJSON(), 
            "amount": amount, 
            "currency": currency?.encodeToJSON()
        ])
        

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
