//
// ConnectAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class ConnectAPI: APIBase {
    /**

     - parameter username: (form)  (optional)
     - parameter password: (form)  (optional)
     - parameter grantType: (form)  (optional)
     - parameter scope: (form)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiConnectTokenPost(username: String? = nil, password: String? = nil, grantType: String? = nil, scope: String? = nil, completion: @escaping ((_ data: AuthToken?,_ error: Error?) -> Void)) {
        apiConnectTokenPostWithRequestBuilder(username: username, password: password, grantType: grantType, scope: scope).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - POST /api/connect/token
     - examples: [{contentType=application/json, example={
  "access_token" : "aeiou",
  "refresh_token" : "aeiou",
  "scope" : "aeiou",
  "id_token" : "aeiou",
  "token_type" : "aeiou",
  "expires_in" : "aeiou"
}}]
     
     - parameter username: (form)  (optional)
     - parameter password: (form)  (optional)
     - parameter grantType: (form)  (optional)
     - parameter scope: (form)  (optional)

     - returns: RequestBuilder<AuthToken> 
     */
    open class func apiConnectTokenPostWithRequestBuilder(username: String? = nil, password: String? = nil, grantType: String? = nil, scope: String? = nil) -> RequestBuilder<AuthToken> {
        let path = "/api/connect/token"
        let URLString = SwaggerClientAPI.basePath + path
        let formParams: [String:Any?] = [
            "username": username,
            "password": password,
            "grant_type": grantType,
            "scope": scope
        ]

        let nonNullParameters = APIHelper.rejectNil(formParams)
        let parameters = APIHelper.convertBoolToString(nonNullParameters)

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<AuthToken>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
