//
// TransactionsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class TransactionsAPI: APIBase {
    /**

     - parameter page: (query)  (optional)
     - parameter pagesize: (query)  (optional)
     - parameter authorization: (header) Authorization header parameter (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTransactionsGet(page: Int32? = nil, pagesize: Int32? = nil, authorization: String? = nil, completion: @escaping ((_ data: [Transaction]?,_ error: Error?) -> Void)) {
        apiTransactionsGetWithRequestBuilder(page: page, pagesize: pagesize, authorization: authorization).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /api/Transactions
     - examples: [{contentType=application/json, example=[ {
  "amount" : 1.3579000000000001069366817318950779736042022705078125,
  "paymentMethod" : "aeiou",
  "treeCount" : 123,
  "currency" : "aeiou",
  "id" : 123,
  "creationDate" : "2000-01-23T04:56:07.000+00:00",
  "userId" : "aeiou",
  "projectId" : 123,
  "finishedDate" : "2000-01-23T04:56:07.000+00:00",
  "status" : "aeiou"
} ]}]
     
     - parameter page: (query)  (optional)
     - parameter pagesize: (query)  (optional)
     - parameter authorization: (header) Authorization header parameter (optional)

     - returns: RequestBuilder<[Transaction]> 
     */
    open class func apiTransactionsGetWithRequestBuilder(page: Int32? = nil, pagesize: Int32? = nil, authorization: String? = nil) -> RequestBuilder<[Transaction]> {
        let path = "/api/Transactions"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "page": page?.encodeToJSON(), 
            "pagesize": pagesize?.encodeToJSON()
        ])
        
        let nillableHeaders: [String: Any?] = [
            "Authorization": authorization
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Transaction]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

}
