//
// AuthToken.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class AuthToken: JSONEncodable {
    public var scope: String?
    public var tokenType: String?
    public var accessToken: String?
    public var expiresIn: String?
    public var refreshToken: String?
    public var idToken: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["scope"] = self.scope
        nillableDictionary["token_type"] = self.tokenType
        nillableDictionary["access_token"] = self.accessToken
        nillableDictionary["expires_in"] = self.expiresIn
        nillableDictionary["refresh_token"] = self.refreshToken
        nillableDictionary["id_token"] = self.idToken
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
