//
// UserInfoModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class UserInfoModel: JSONEncodable {
    public enum Gender: Int32 { 
        case number0 = 0
        case number1 = 1
    }
    public var name: String?
    public var gender: Gender?
    public var birthday: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["gender"] = self.gender?.rawValue
        nillableDictionary["birthday"] = self.birthday
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
